const LOCAL_ITEM_INFO_LIST = 'LOCAL_ITEM_INFO_LIST'
const LOCAL_ITEM_INFO_MAP = 'LOCAL_ITEM_INFO_MAP'
const LOCAL_ITEM_VAlUE_MAP = 'LOCAL_ITEM_VAlUE_MAP'

export default{
    LOCAL_ITEM_INFO_LIST,LOCAL_ITEM_INFO_MAP,LOCAL_ITEM_VAlUE_MAP
}