const LOCAL_ITEM_INFO_LIST = 'LOCAL_ITEM_INFO_LIST'
const LOCAL_ITEM_INFO_MAP = 'LOCAL_ITEM_INFO_MAP'
const LOCAL_ITEM_VAlUE_MAP = 'LOCAL_ITEM_VAlUE_MAP'
const LOCAL_PENGUIN_DATA = 'LOCAL_PENGUIN_DATA'

export default{
    LOCAL_ITEM_INFO_LIST,LOCAL_ITEM_INFO_MAP,LOCAL_ITEM_VAlUE_MAP,LOCAL_PENGUIN_DATA
}